version: "2.0"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - 5432:${DB_PORT}