version: "2.0"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - 5432:${DB_PORT}
  pg_admin:
    image: "dpage/pgadmin4:5.1"
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - 5050
